import type { Metadata } from "next";
import "./globals.css";
import ToggleContextProvider from "@/context/ToggleState";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-main">
        <ToggleContextProvider>{children}</ToggleContextProvider>
      </body>
    </html>
  );
}
